### ISSUE TITLE
Can not be seen Compass

### ISSUE THREAD

**Issue by rk2026** [SteRiccio/my-arena-mobile#7]
Dear Developer,
This application is amazing then official one. There should be a compass symbol near coordinate value, but I cannot see the icon. There is just a map symbol which redirects to map only. What we want here is
 We manually put the coordinate in its field, and we search the sampling point location first. The compass will guide us to navigate the desired location. Unfortunately, I cannot see the compass icon or symbol. maybe not seeing due to color combination of the symbol and background color of the theme or something else. My mobile phone model is Galaxy A73 5G (model SM-A736B. Please fix it. Thank you in advance.

**Comment by rk2026** [comment]
The compass shows for pre-entered as described in this link https://docs.google.com/document/d/1GWerrExvbdT5oOOlwdkE9pptK4pVbQxwtgaSNPasmKA/view#heading=h.2zfmd5e1ck00
But in my case the user defines his sample plot entering during survey as I was interested previous comment.

Another comment: when I define hide in arena mobile for calculated attribute in arena desktop form design it still show the hidden attribute. Can you check it?

**Comment by rk2026** [comment]
The compass shows for pre-entered as described in this link https://docs.google.com/document/d/1GWerrExvbdT5oOOlwdkE9pptK4pVbQxwtgaSNPasmKA/view#heading=h.2zfmd5e1ck00
But in my case the user defines his sample plot entering during survey as I was interested previous comment. It may be the reason I cannot see the compass. Am I right?

**Comment by rk2026** [comment]
The compass shows for pre-entered as described in this link https://docs.google.com/document/d/1GWerrExvbdT5oOOlwdkE9pptK4pVbQxwtgaSNPasmKA/view#heading=h.2zfmd5e1ck00
But in my case the user defines his sample plot entering during survey as I was interested previous comment. It may be the reason I cannot see the compass. Am I right?

Another issue is that once after checking out hide in arena mobile for my calculated attribute it still show the attribute? can you check this one? Thank you.

**Comment by SteRiccio** [comment]
The compass is shown only if in the coordinate attribute there is a validation rule using the "distance" function; issue with hidden calculated attributes has been fixed. 
Many thanks for your feedback!
